feature: Nested Span support for fonts
privateOmega/html-to-docx pull request #158
Opened 2022-11-07 17:30 UTC by nicolasiscoding

2022-11-09 17:04 UTC, privateOmega requested changes

2022-11-09 17:04 UTC, privateOmega commented on src/helpers/xml-builder.js
> +          dfs(spanFragment);
```js
spanFragment.flat(Infinity);
runFragmentsArray.push(...spanFragment);
```
 should do the same trick I guess

2022-11-10 01:24 UTC, nicolasiscoding commented on example/example-node.js
> +            <li><span style="font-size:10pt"><span style="color:##e28743">I am a teacup <strong><span style="color:#595959">A strong teacup</span></strong> Managed Environment.</span></span></li>
Done

2022-11-10 01:24 UTC, nicolasiscoding commented on src/helpers/xml-builder.js
> +          dfs(spanFragment);
Done

2022-11-10 03:23 UTC, privateOmega commented on src/helpers/xml-builder.js
> +      } else if (isVNode(tempVNode) && tempVNode.tagName === 'span') {
Since isVNode is common in 2 if conditions, make it nested

2022-11-10 04:33 UTC, nicolasiscoding commented on src/helpers/xml-builder.js
> +      } else if (isVNode(tempVNode) && tempVNode.tagName === 'span') {
Done

2022-11-10 17:09 UTC, privateOmega commented
@nicolasiscoding Please rebase this branch

2022-11-10 18:10 UTC, nicolasiscoding commented
Rebased but did not merge develop into my branch

2022-11-12 16:31 UTC, privateOmega approved these changes
LGTM

2022-11-12 16:31 UTC, merged